const ru = {
                toolbarExport: 'Экспорт',
                toolbarColumnsButtonText: 'Колонки',
                toolbarFilterButtonText: 'Фильтры',
                toolbarDensity: 'Плотность',
                filterPanelAddFilter: 'Добавить фильтр',
                filterOperatorContains: 'Содержит',
                filterOperatorEquals: 'Равно',
                filterOperatorStartsWith: 'Начинается с',
                filterOperatorEndsWith: 'Заканчивается на',
                filterOperatorIs: 'Является',
                filterOperatorNot: 'Не является',
                filterOperatorAfter: 'Позже',
                filterOperatorOnOrAfter: 'На или позже',
                filterOperatorBefore: 'Ранее',
                filterOperatorOnOrBefore: 'На или ранее',
                columnMenuLabelHideColumn: 'Скрыть колонку',
                columnMenuLabelShowColumnsSelector: 'Показать выбор колонок',
                columnMenuFilterButtonText: 'Фильтр',
                columnMenuHideColumn: 'Скрыть',
                columnMenuUnsort: 'Отменить сортировку',
                columnMenuSortAsc: 'Сортировка по возрастанию',
                columnMenuSortDesc: 'Сортировка по убыванию',
                densityStandard: 'Стандартная плотность',
                densityCompact: 'Компактная плотность',
                densityComfortable: 'Комфортная плотность',
                noRowsLabel: 'Здесь пока нету студентов',
                errorOverlayDefaultLabel: 'Ошибка загрузки данных',
                footerPageNumberInputTooltipLabel: 'Номер страницы',
                footerPagination: '{from}-{to} из {count}',
                checkboxSelectionHeaderName: '',
                filterPanelDeleteIconTitle: 'Удалить',
                filterPanelOperators: 'Операторы',
                filterFormApplyButtonText: 'Применить',
                filterFormClearButtonText: 'Очистить',
                columnMenuThirdStateText: 'Частично выбрано',
                toolbarQuickFilterPlaceholder: 'Поиск…',
                toolbarQuickFilterLabel: 'Поиск',
};
const ruForPlan = {
    toolbarExport: 'Экспорт',
    toolbarColumnsButtonText: 'Колонки',
    toolbarFilterButtonText: 'Фильтры',
    toolbarDensity: 'Плотность',
    filterPanelAddFilter: 'Добавить фильтр',
    filterOperatorContains: 'Содержит',
    filterOperatorEquals: 'Равно',
    filterOperatorStartsWith: 'Начинается с',
    filterOperatorEndsWith: 'Заканчивается на',
    filterOperatorIs: 'Является',
    filterOperatorNot: 'Не является',
    filterOperatorAfter: 'Позже',
    filterOperatorOnOrAfter: 'На или позже',
    filterOperatorBefore: 'Ранее',
    filterOperatorOnOrBefore: 'На или ранее',
    columnMenuLabelHideColumn: 'Скрыть колонку',
    columnMenuLabelShowColumnsSelector: 'Показать выбор колонок',
    columnMenuFilterButtonText: 'Фильтр',
    columnMenuHideColumn: 'Скрыть',
    columnMenuUnsort: 'Отменить сортировку',
    columnMenuSortAsc: 'Сортировка по возрастанию',
    columnMenuSortDesc: 'Сортировка по убыванию',
    densityStandard: 'Стандартная плотность',
    densityCompact: 'Компактная плотность',
    densityComfortable: 'Комфортная плотность',
    noRowsLabel: 'Учебный план пока не настроен',
    errorOverlayDefaultLabel: 'Ошибка загрузки данных',
    footerPageNumberInputTooltipLabel: 'Номер страницы',
    footerPagination: '{from}-{to} из {count}',
    checkboxSelectionHeaderName: '',
    filterPanelDeleteIconTitle: 'Удалить',
    filterPanelOperators: 'Операторы',
    filterFormApplyButtonText: 'Применить',
    filterFormClearButtonText: 'Очистить',
    columnMenuThirdStateText: 'Частично выбрано',
    toolbarQuickFilterPlaceholder: 'Поиск…',
    toolbarQuickFilterLabel: 'Поиск',
};
export default { ru, ruForPlan };