import express from 'express';
import cors from 'cors';
import * as sql from 'mssql';
import sqlConfig from './db/config/config';
import { connectToDatabase } from './db/connection/connection';
import registerUser from './db/post/register';
import authorizationUser from './db/post/authorization';
import addGroup from './db/post/createGroup';
import addLesson from './db/post/createLessons';
import addRoom from './db/post/createRooms';
import CreateDateSecondSemester from './db/post/createsecondsemesterdate';
import addMembers from './db/post/AddMembers';
import addPSchedules from './db/post/AddPSchedule';
import changeGroup from './db/post/ChangeGroup';
import addGeneralBurden from './db/post/createBurden';
import addTSchedules from './db/post/AddTSchedule';
import addSubGeneralBurden from './db/post/createSubBurden';
import addPlans from './db/post/AddPlan';
import removeGroup from './db/delete/removeGroup';
import deleteMember from './db/delete/DeleteMember';
import deletePSchedule from './db/delete/DeletePSchedule';
import deleteTSchedule from './db/delete/DeleteTSchedule';
import logOut from './db/delete/LogOut';
import deletePlanFirstSemester from './db/delete/DeletePlanFirstSemester';
import deletePlanSecondSemester from './db/delete/DeletePlanSecondSemester';
import { getTeacherInBurden } from './db/get/GetTeacherInBurden';
import { getPlan } from './db/get/GetPlan';
import { getIDStudent } from './db/get/GetIDStudent';
import { getAllgroups } from './db/get/GetAllGroups';
import { getAlllessonss } from './db/get/GetAllLessons';
import { getAllrooms } from './db/get/GetAllRooms';
import { getTeacherID } from './db/get/GetTeacher';
import { getRoleByUserID } from './db/get/getRoleID';
import { getMembers } from './db/get/GetMembers';
import { getAllteachers } from './db/get/GetAllTeachers';
import { getAllSubBurden } from './db/get/GetAllSubBurden';
import { getPschedulePartNumerator } from './db/get/GetAllPartPScheduleNumerator';
import { getPschedulePartDenumerator } from './db/get/GetAllPartPScheduleDenumerator';
import { getTSchedulePart } from './db/get/GetAllTSchedluePart';
import { getStudentSchedulePart } from './db/get/GetAllStudentSchedluePart';
import { getStudentPSchedulePart } from './db/get/GetAllStudentPSchedluePart';
import { getTeacherSchedulePart } from './db/get/GetAllTeacherSchedluePart';
import { getTeacherPSchedulePart } from './db/get/GetAllTeacherPSchedluePart';
import { getNameGroupInGroup } from './db/get/GetNameGroupInConstructor';
import { getNameGroupInStudent } from './db/get/GetNameGroupInStudent';
import { getNameGroupInTeacher } from './db/get/GetNameGroupInTeacher';
import { getPlanLesson } from './db/get/GetPlanLesson';
import ValidateDataGroup from './db/get/validatedatagroup';
import { StartSecondSemester } from './db/get/StartSecondSemester';
import cookieParser from 'cookie-parser';
import { startTelegramBot } from './Telegram_bot/Telegram_bot';

const app = express();
const corsOptions = {
    origin: ["http://localhost:49230"],
    credentials: true,
};
app.use(cors(corsOptions));
app.options('*', cors());
app.use(express.json());
app.use(cookieParser());
connectToDatabase().then(() => {
    startTelegramBot();
    app.get('/', (req, res) => {
        res.json({ status: "Окей" });
    });

    app.listen(8080, () => {
        console.log('Сервер запущен на порту: 8080');
    });
});
app.get('/StartSecondSemester', StartSecondSemester);
app.get('/ID_Student', getIDStudent);
app.get('/RoleID', getRoleByUserID);
app.get('/ID_Teacher', getTeacherID);
app.get('/AllGroups', getAllgroups);
app.get('/AllLessons', getAlllessonss);
app.get('/AllRooms', getAllrooms);
app.get('/AllTeachers', getAllteachers);
app.get('/AllSubBurden', getAllSubBurden);
app.get('/Plan', getPlan);
app.get('/student/StudentSchedulePart', getStudentSchedulePart);
app.get('/student/StudentPSchedulePart', getStudentPSchedulePart);
app.get('/student/GroupInStudent', getNameGroupInStudent);
app.get('/administrator/PScheduleNumeratorPart', getPschedulePartNumerator);
app.get('/administrator/PScheduleDenumeratorPart', getPschedulePartDenumerator);
app.get('/administrator/TSchedulePart', getTSchedulePart);
app.get('/administrator/GroupInConstructor', getNameGroupInGroup);
app.get('/administrator/GetTeacherInBurden', getTeacherInBurden);
app.get('/administrator/GetPlanLesson', getPlanLesson);
app.get('/teacher/TeacherSchedulePart', getTeacherSchedulePart);
app.get('/teacher/TeacherPSchedulePart', getTeacherPSchedulePart);
app.get('/teacher/GroupInTeacher', getNameGroupInTeacher);
app.get('/teacher/validategroup', ValidateDataGroup);
app.get('/teacher/Members', getMembers);
app.post('/teacher/AddMember', addMembers);
app.post('/logout', logOut);
app.post('/register', registerUser);
app.post('/authorization', authorizationUser);
app.post('/teacher/addGroup', addGroup);
app.post('/administrator/addRoom', addRoom);
app.post('/administrator/addLesson', addLesson);
app.post('/administrator/addDateSecondSemester', CreateDateSecondSemester);
app.post('/administrator/addPSchedules', addPSchedules);
app.post('/administrator/addTSchedules', addTSchedules);
app.post('/administrator/addGeneralBurden', addGeneralBurden);
app.post('/administrator/addSubGeneralBurden', addSubGeneralBurden);
app.post('/administrator/addPlan', addPlans);
app.post('/administrator/changeGroup', changeGroup);
app.delete('/teacher/exitgroup', removeGroup);
app.delete('/teacher/deleteStudentInGroup', deleteMember);
app.delete('/administrator/deleteFirstPlan', deletePlanFirstSemester);
app.delete('/administrator/deleteSecondPlan', deletePlanSecondSemester);
app.delete('/administrator/deletePSchedule', deletePSchedule);
app.delete('/administrator/deleteTSchedule', deleteTSchedule);